export type SeedStopInput = {
  kind: "origin" | "stay";
  city: string;
  country: string;
  arrivalDate: string | null;
  departureDate: string | null;
  notes: string;
};

export const seededItineraryStops: SeedStopInput[] = [
  {
    kind: "origin",
    city: "Vancouver",
    country: "Canada",
    arrivalDate: null,
    departureDate: "2026-02-20",
    notes: "",
  },
  {
    kind: "stay",
    city: "Porto",
    country: "Portugal",
    arrivalDate: "2026-02-21",
    departureDate: "2026-03-02",
    notes: "",
  },
  {
    kind: "stay",
    city: "Lisbon",
    country: "Portugal",
    arrivalDate: "2026-03-02",
    departureDate: "2026-03-09",
    notes: "",
  },
  {
    kind: "stay",
    city: "Faro",
    country: "Portugal",
    arrivalDate: "2026-03-09",
    departureDate: "2026-03-16",
    notes: "",
  },
  {
    kind: "stay",
    city: "Lisbon",
    country: "Portugal",
    arrivalDate: "2026-03-16",
    departureDate: "2026-03-17",
    notes: "",
  },
  {
    kind: "stay",
    city: "Barcelona",
    country: "Spain",
    arrivalDate: "2026-03-17",
    departureDate: "2026-03-22",
    notes: "",
  },
  {
    kind: "stay",
    city: "Valencia",
    country: "Spain",
    arrivalDate: "2026-03-22",
    departureDate: "2026-03-29",
    notes: "",
  },
  {
    kind: "stay",
    city: "Alicante",
    country: "Spain",
    arrivalDate: "2026-03-29",
    departureDate: "2026-04-05",
    notes: "",
  },
  {
    kind: "stay",
    city: "Madrid",
    country: "Spain",
    arrivalDate: "2026-04-05",
    departureDate: "2026-04-10",
    notes: "",
  },
  {
    kind: "stay",
    city: "Amsterdam",
    country: "Netherlands",
    arrivalDate: "2026-04-10",
    departureDate: "2026-04-13",
    notes: "",
  },
  {
    kind: "stay",
    city: "Hamburg",
    country: "Germany",
    arrivalDate: "2026-04-13",
    departureDate: "2026-04-16",
    notes: "",
  },
  {
    kind: "stay",
    city: "Copenhagen",
    country: "Denmark",
    arrivalDate: "2026-04-16",
    departureDate: "2026-04-20",
    notes: "",
  },
  {
    kind: "stay",
    city: "Stockholm",
    country: "Sweden",
    arrivalDate: "2026-04-20",
    departureDate: "2026-04-25",
    notes: "",
  },
  {
    kind: "stay",
    city: "Oslo",
    country: "Norway",
    arrivalDate: "2026-04-25",
    departureDate: "2026-04-30",
    notes: "",
  },
  {
    kind: "stay",
    city: "Warsaw",
    country: "Poland",
    arrivalDate: "2026-04-30",
    departureDate: "2026-05-21",
    notes: "",
  },
  {
    kind: "stay",
    city: "Krakow",
    country: "Poland",
    arrivalDate: "2026-05-21",
    departureDate: "2026-05-26",
    notes: "",
  },
  {
    kind: "stay",
    city: "Zakopane",
    country: "Poland",
    arrivalDate: "2026-05-26",
    departureDate: "2026-06-01",
    notes: "",
  },
  {
    kind: "stay",
    city: "Wroclaw",
    country: "Poland",
    arrivalDate: "2026-06-01",
    departureDate: "2026-06-04",
    notes: "",
  },
  {
    kind: "stay",
    city: "Berlin",
    country: "Germany",
    arrivalDate: "2026-06-04",
    departureDate: "2026-06-06",
    notes: "",
  },
  {
    kind: "stay",
    city: "Dublin",
    country: "Ireland",
    arrivalDate: "2026-06-06",
    departureDate: "2026-06-14",
    notes: "",
  },
  {
    kind: "stay",
    city: "Limerick",
    country: "Ireland",
    arrivalDate: "2026-06-14",
    departureDate: "2026-06-19",
    notes: "",
  },
  {
    kind: "stay",
    city: "Cork",
    country: "Ireland",
    arrivalDate: "2026-06-19",
    departureDate: "2026-06-24",
    notes: "",
  },
  {
    kind: "stay",
    city: "Dublin",
    country: "Ireland",
    arrivalDate: "2026-06-24",
    departureDate: "2026-06-27",
    notes: "",
  },
];

export const seededTravelModes = [
  "air",
  "ground",
  "ground",
  "ground",
  "air",
  "ground",
  "ground",
  "ground",
  "air",
  "ground",
  "ground",
  "ground",
  "ground",
  "air",
  "ground",
  "ground",
  "ground",
  "ground",
  "air",
  "ground",
  "ground",
  "ground",
] as const;
